#include "gba.h"
#include "logic.h"
#include "draw.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/startScreen.h"
#include "images/endScreen.h"
#include "images/sprites.h"

#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    APP_INIT,
    APP,
    NEW_LEVEL,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.

    REG_DISPCNT = MODE3 | BG2_ENABLE | OBJ_ENABLE | SPRITES_DIMENSION_TYPE;

    setUpSprites();


    /*setPixel(30, 30, MAGENTA);
    setPixel(100, 50, RED);
    drawImageDMA(40, 40, 15, 16, (u16 *)ship);*/


    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while (1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            if (currentAppState.alienList != NULL) {
                clearLevel(&currentAppState, 0);
                clearSprites();
            }
            state = START;
        }

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the start state here.
                drawFullScreenImageDMA(startScreen);

                state = START_NODRAW;
                break;
            case START_NODRAW:
                // TA-TODO: Check for a button press here to start the app.
                // Start the app by switching the state to APP_INIT.

                if (KEY_JUST_PRESSED(BUTTON_A | BUTTON_START, currentButtons, previousButtons)) {
                    state = APP_INIT;
                }

                break;
            case APP_INIT:
                // Initialize the app. Switch to the APP state.
                initializeAppState(&currentAppState);

                drawLevelText(currentAppState.level);

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);

                state = APP;
                break;
            case APP:
                // Process the app for one frame, store the next state
                //nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);
                processAppState(&currentAppState, previousButtons, currentButtons);

                // Wait for VBlank before we do any drawing.
                waitForVBlank();

                // Draw the current state

                drawAppState(&currentAppState);

                // Now set the current state as the next state for the next iter.
                //currentAppState = nextAppState;

                // Check if the app is exiting. If it is, then go to the exit state.
                if (currentAppState.nextLevel) {
                    state = NEW_LEVEL;
                } else if (currentAppState.gameOver) {
                    state = APP_EXIT;
                }

                break;
            case NEW_LEVEL:

                currentAppState.nextLevel = 0;

                drawLevelText(currentAppState.level);

                initializeNextLevel(&currentAppState);

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);

                state = APP;

                break;
            case APP_EXIT:
                // Wait for VBlank
                waitForVBlank();

                clearLevel(&currentAppState, 0);
                clearSprites();

                // TA-TODO: Draw the exit / gameover screen
                drawFullScreenImageDMA(endScreen);

                state = APP_EXIT_NODRAW;
                break;
            case APP_EXIT_NODRAW:
                //drawFullScreenImageDMA(endScreen);

                waitForVBlank();

                drawGameOverScreen(&currentAppState);
                // TA-TODO: Check for a button press here to go back to the start screen
                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    state = START;
                }
                break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}